import { StyleSheet } from "react-native";

export const noteContentStyle = {
  fontSize: 15,
  lineHeight: 21,
  flexWrap: "wrap" as const,
};

export const styles = StyleSheet.create({
  centerLoading: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f3f6ff",
    gap: 12,
  },
  centerLoadingText: {
    color: "#4b5563",
    fontWeight: "600",
  },
  onboardingScreen: {
    flex: 1,
    backgroundColor: "#eef3ff",
    justifyContent: "center",
    padding: 22,
  },
  onboardingCard: {
    backgroundColor: "#ffffff",
    borderRadius: 24,
    padding: 22,
    borderWidth: 1,
    borderColor: "#dbe5ff",
    gap: 14,
    shadowColor: "#1e3a8a",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 4,
  },
  onboardingBrand: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  onboardingBrandIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#2563eb",
  },
  onboardingBrandText: {
    color: "#1e3a8a",
    fontWeight: "900",
    fontSize: 18,
  },
  onboardingTitle: {
    fontSize: 28,
    fontWeight: "900",
    color: "#0f172a",
  },
  onboardingSubTitle: {
    color: "#475569",
    fontSize: 16,
    marginBottom: 6,
  },
  inputLabel: {
    color: "#334155",
    fontWeight: "700",
  },
  onboardingInput: {
    borderWidth: 1,
    borderColor: "#bfdbfe",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: "#0f172a",
    backgroundColor: "#f8fbff",
  },
  oauthButton: {
    backgroundColor: "#2563eb",
    height: 50,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#1d4ed8",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.24,
    shadowRadius: 8,
    elevation: 3,
  },
  oauthButtonText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 16,
  },
  oauthErrorText: {
    color: "#dc2626",
    fontSize: 12,
  },
  onboardingHint: {
    color: "#64748b",
    fontSize: 13,
    lineHeight: 19,
  },
  screen: {
    flex: 1,
    backgroundColor: "#f6f8ff",
  },
  header: {
    paddingHorizontal: 14,
    paddingBottom: 10,
    paddingTop: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  headerAccountButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  headerAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: "#dbeafe",
  },
  headerAppName: {
    color: "#1d4ed8",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  headerName: {
    fontWeight: "900",
    fontSize: 16,
    color: "#0f172a",
  },
  headerMeta: {
    color: "#64748b",
    fontSize: 12,
  },
  tabBar: {
    flexDirection: "row",
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginHorizontal: 10,
    marginTop: 8,
    backgroundColor: "#eaf1ff",
    borderRadius: 14,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    borderRadius: 10,
  },
  tabButtonActive: {
    backgroundColor: "#ffffff",
  },
  tabButtonText: {
    color: "#475569",
    fontWeight: "700",
  },
  tabButtonTextActive: {
    color: "#1e40af",
  },
  accountMenuPanel: {
    backgroundColor: "#f8fbff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
    gap: 16,
    width: "100%",
    elevation: 10,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: -5 },
  },
  bottomSheetHandle: {
    width: 40,
    height: 5,
    backgroundColor: "#cbd5e1",
    borderRadius: 3,
    alignSelf: "center",
    marginBottom: 8,
  },
  accountMenuBackdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 40,
  },
  settingsTitle: {
    fontWeight: "900",
    fontSize: 16,
    color: "#0f172a",
  },
  devModeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  devModeLabel: {
    color: "#1e293b",
    fontWeight: "700",
  },
  accountSectionTitle: {
    color: "#334155",
    fontWeight: "800",
    marginTop: 2,
  },
  accountRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  accountMain: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
  },
  accountAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
  },
  accountName: {
    color: "#0f172a",
    fontWeight: "700",
  },
  accountHost: {
    color: "#64748b",
    fontSize: 12,
  },
  removeAccountButton: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryButton: {
    backgroundColor: "#dbeafe",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 11,
  },
  secondaryButtonText: {
    color: "#1e3a8a",
    fontWeight: "700",
  },
  addAccountBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 12,
  },
  addAccountBtnText: {
    fontSize: 16,
    fontWeight: "700",
  },
  logoutBtn: {
    marginTop: 16,
    alignItems: "center",
    paddingVertical: 14,
  },
  logoutBtnText: {
    color: "#ef4444",
    fontSize: 15,
    fontWeight: "800",
  },
  errorText: {
    color: "#ef4444",
    fontSize: 13,
    marginTop: 8,
  },
  addAccountCard: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 10,
    gap: 8,
  },
  addAccountTitle: {
    fontWeight: "800",
    fontSize: 13,
  },
  addAccountInput: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  addAccountActions: {
    flexDirection: "row",
    gap: 8,
  },
  addAccountActionButton: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 38,
  },
  addAccountCancelText: {
    fontWeight: "700",
  },
  addAccountLoginText: {
    color: "#ffffff",
    fontWeight: "800",
  },
  timelineLoading: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  timelineLoadingText: {
    color: "#64748b",
  },
  timeline: {
    flex: 1,
    marginTop: 6,
  },
  timelineError: {
    color: "#dc2626",
    paddingHorizontal: 16,
    paddingTop: 10,
  },
  emptyStateCard: {
    margin: 14,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#dbeafe",
    backgroundColor: "#ffffff",
    gap: 10,
  },
  emptyStateTitle: {
    color: "#0f172a",
    fontSize: 15,
    fontWeight: "800",
  },
  emptyStateText: {
    color: "#64748b",
    fontSize: 13,
  },
  noteCard: {
    marginHorizontal: 12,
    marginBottom: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#dbeafe",
    backgroundColor: "#ffffff",
  },
  renoteText: {
    color: "#64748b",
    fontSize: 11,
    marginBottom: 6,
    marginLeft: 0,
  },
  replyPreview: {
    borderRadius: 8,
    padding: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderLeftWidth: 3,
  },
  replyPreviewLabel: {
    fontSize: 12,
    marginBottom: 4,
  },
  replyPreviewContent: {
    flexDirection: "row",
    gap: 6,
    alignItems: "flex-start",
  },
  replyPreviewAvatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
  },
  replyPreviewName: {
    fontSize: 12,
    fontWeight: "700",
  },
  replyPreviewText: {
    fontSize: 12,
  },
  noteRow: {
    flexDirection: "row",
    gap: 10,
    alignItems: "flex-start",
  },
  noteAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  noteMain: {
    flex: 1,
    gap: 6,
    minWidth: 0,
  },
  noteHeaderRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 6,
  },
  noteName: {
    color: "#0f172a",
    fontWeight: "800",
  },
  noteMeta: {
    color: "#64748b",
    fontSize: 12,
  },
  noteContent: {
    color: "#0f172a",
    fontSize: 15,
    lineHeight: 21,
    flexWrap: "wrap",
  },
  mediaContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  mediaItem: {
    flex: 1,
    minWidth: "48%",
    aspectRatio: 1,
    borderRadius: 8,
    overflow: "hidden",
  },
  mediaImage: {
    width: "100%",
    height: "100%",
  },
  mediaFile: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f8fbff",
    gap: 8,
  },
  mediaFileName: {
    fontSize: 12,
    maxWidth: "90%",
  },
  reactionWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 4,
    marginBottom: 6,
  },
  actionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 2,
  },
  actionGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 24,
  },
  actionItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 4,
  },
  actionCount: {
    fontSize: 13,
    fontWeight: "600",
  },

  replyComposer: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 8,
    gap: 8,
  },
  replyInput: {
    minHeight: 48,
    textAlignVertical: "top",
    fontSize: 14,
  },
  replySendButton: {
    alignSelf: "flex-end",
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  replySendButtonDisabled: {
    opacity: 0.6,
  },
  replySendText: {
    color: "#ffffff",
    fontWeight: "800",
    fontSize: 12,
  },
  reactionButton: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#dbeafe",
    paddingHorizontal: 8,
    paddingVertical: 4,
    gap: 4,
    backgroundColor: "#f8fbff",
  },
  reactionActive: {
    borderColor: "#60a5fa",
    backgroundColor: "#dbeafe",
  },
  reactionText: {
    fontSize: 12,
  },
  reactionCount: {
    color: "#334155",
    fontSize: 11,
  },
  devPanel: {
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    backgroundColor: "#0f172a",
    padding: 10,
    gap: 2,
  },
  devTitle: {
    color: "#f8fafc",
    fontWeight: "800",
    marginBottom: 4,
  },
  devText: {
    color: "#cbd5e1",
    fontSize: 11,
  },
  quoteCard: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 10,
    marginTop: 8,
    gap: 6,
  },
  quoteHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
  },
  quoteAvatar: {
    width: 20,
    height: 20,
    borderRadius: 10,
  },
  quoteName: {
    fontWeight: "800",
    fontSize: 13,
  },
  quoteMeta: {
    fontSize: 11,
  },
  quoteMediaContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
    marginTop: 4,
  },
  quoteMediaItem: {
    flex: 1,
    minWidth: "48%",
    aspectRatio: 1.5,
    borderRadius: 6,
    overflow: "hidden",
  },
  quoteMediaImage: {
    width: "100%",
    height: "100%",
  },
  quoteMediaFile: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: 4,
  },
  quoteMediaFileName: {
    fontSize: 10,
    maxWidth: "90%",
  },
  buttonPressed: {
    opacity: 0.75,
  },
  bottomNav: {
    flexDirection: "row",
    borderTopWidth: 1,
    paddingBottom: 8,
    paddingTop: 8,
  },
  bottomNavTab: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  fab: {
    position: "absolute",
    right: 20,
    bottom: 80,
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: "center",
    alignItems: "center",
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
});
